// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nano.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	nano.proto

It has these top-level messages:
	Push
	Session
	Msg
	Request
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPCType int32

const (
	RPCType_Sys  RPCType = 0
	RPCType_User RPCType = 1
)

var RPCType_name = map[int32]string{
	0: "Sys",
	1: "User",
}
var RPCType_value = map[string]int32{
	"Sys":  0,
	"User": 1,
}

func (x RPCType) String() string {
	return proto.EnumName(RPCType_name, int32(x))
}
func (RPCType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Push struct {
	Route string `protobuf:"bytes,1,opt,name=Route" json:"Route,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Push) Reset()                    { *m = Push{} }
func (m *Push) String() string            { return proto.CompactTextString(m) }
func (*Push) ProtoMessage()               {}
func (*Push) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Push) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Push) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Session struct {
	ID   int64             `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Data map[string]string `protobuf:"bytes,2,rep,name=Data" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Session) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Session) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type Msg struct {
	ID    uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Route string `protobuf:"bytes,2,opt,name=Route" json:"Route,omitempty"`
	Data  []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Reply string `protobuf:"bytes,4,opt,name=Reply" json:"Reply,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Msg) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Msg) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Msg) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

type Request struct {
	Type    RPCType  `protobuf:"varint,1,opt,name=Type,enum=protos.RPCType" json:"Type,omitempty"`
	Session *Session `protobuf:"bytes,2,opt,name=Session" json:"Session,omitempty"`
	Msg     *Msg     `protobuf:"bytes,3,opt,name=Msg" json:"Msg,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Request) GetType() RPCType {
	if m != nil {
		return m.Type
	}
	return RPCType_Sys
}

func (m *Request) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *Request) GetMsg() *Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Push)(nil), "protos.Push")
	proto.RegisterType((*Session)(nil), "protos.Session")
	proto.RegisterType((*Msg)(nil), "protos.Msg")
	proto.RegisterType((*Request)(nil), "protos.Request")
	proto.RegisterEnum("protos.RPCType", RPCType_name, RPCType_value)
}

func init() { proto.RegisterFile("nano.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x75, 0xd9, 0x55, 0x64, 0x30, 0x95, 0x4c, 0x3c, 0xa0, 0xd1, 0xa4, 0xc1, 0x0b, 0x9a, 0x48,
	0x0c, 0x1e, 0x34, 0x5e, 0xc5, 0x43, 0x0f, 0x4d, 0x9a, 0xad, 0xfd, 0x00, 0x4c, 0x36, 0xd5, 0xd8,
	0x00, 0xb2, 0x60, 0xe4, 0xe8, 0x9f, 0x9b, 0x9d, 0xa5, 0x5b, 0x0f, 0x9e, 0x98, 0x79, 0xf3, 0x98,
	0x37, 0xef, 0x2d, 0x40, 0x55, 0x56, 0x75, 0xd6, 0xb4, 0x75, 0x57, 0xe3, 0x01, 0x7d, 0x74, 0x72,
	0x0b, 0x62, 0xd1, 0xeb, 0x37, 0x3c, 0x81, 0x7d, 0x59, 0xf7, 0x9d, 0x8a, 0xd9, 0x94, 0xa5, 0x81,
	0xb4, 0x0d, 0x22, 0x88, 0xa2, 0xec, 0xca, 0xd8, 0x9b, 0xb2, 0xf4, 0x48, 0x52, 0x9d, 0xfc, 0x30,
	0xf0, 0x97, 0x4a, 0xeb, 0xf7, 0xba, 0xc2, 0x09, 0x78, 0xb3, 0x82, 0x7e, 0xe1, 0xd2, 0x9b, 0x15,
	0x78, 0xe3, 0xf8, 0x3c, 0x0d, 0xf3, 0x53, 0xab, 0xa5, 0xb3, 0x91, 0x9e, 0x99, 0xd9, 0x73, 0xd5,
	0xb5, 0x83, 0x5d, 0x75, 0x76, 0x0f, 0x81, 0x83, 0x30, 0x02, 0xfe, 0xa1, 0x86, 0x51, 0xdf, 0x94,
	0xe6, 0xa6, 0xaf, 0x72, 0xd3, 0x2b, 0x92, 0x0f, 0xa4, 0x6d, 0x1e, 0xbd, 0x07, 0x96, 0xac, 0x80,
	0xcf, 0xf5, 0xfa, 0x8f, 0xbc, 0x20, 0x79, 0x67, 0xc2, 0xfb, 0xcf, 0x04, 0xdf, 0x99, 0x20, 0xa6,
	0x6a, 0x36, 0x43, 0x2c, 0x46, 0xa6, 0x69, 0x92, 0x6f, 0xf0, 0xa5, 0xfa, 0xec, 0x95, 0xee, 0xf0,
	0x12, 0xc4, 0xcb, 0xd0, 0xd8, 0x38, 0x26, 0xf9, 0xf1, 0xd6, 0x89, 0x5c, 0x3c, 0x19, 0x58, 0xd2,
	0x10, 0xaf, 0x5c, 0x12, 0xa4, 0x18, 0xee, 0x78, 0x23, 0x2c, 0x5d, 0x52, 0x17, 0x74, 0x31, 0xdd,
	0x10, 0xe6, 0xe1, 0x96, 0x36, 0xd7, 0x6b, 0x69, 0xf0, 0xeb, 0x73, 0xf0, 0xc7, 0xd5, 0xe8, 0x03,
	0x5f, 0x0e, 0x3a, 0xda, 0xc3, 0x43, 0x10, 0x2b, 0xad, 0xda, 0x88, 0xbd, 0xda, 0xc7, 0xba, 0xfb,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xd3, 0x2d, 0x6f, 0xc1, 0x01, 0x00, 0x00,
}
